// AUTHENTICATION
export const USER_LOADED = 'USER_LOADED'
export const REQUEST_USER = 'REQUEST_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
// ALERTS
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// COMPANY MANAGEMENT
export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const RECEIVE_COMPANIES = 'RECEIVE_COMPANIES'
export const FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL'
// LOADERS
export const LOADING = 'LOADING'
export const STOP_LOADING = 'STOP_LOADING'
// USER MANAGEMENT
export const FETCH_USERS = 'FETCH_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const FAILED_FETCH_USERS = 'FAILED_FETCH_USERS'
// STATS
export const FETCH_STATS = 'FETCH_STATS'
// APPS
export const FETCH_APPS = 'FETCH_APPS'
export const RECEIVE_APPS = 'RECEIVE_APPS'
export const FAILED_FETCH_APPS = 'FAILED_FETCH_APPS'
export const FETCH_SINGLE_APP = 'FETCH_SINGLE_APP'
export const RECEIVE_SINGLE_APP = 'RECEIVE_SINGLE_APP'
export const FAILED_FETCH_SINGLE_APP = 'FAILED_FETCH_SINGLE_APP'
