// AUTHENTICATION
export const USER_LOADED = 'USER_LOADED'
export const REQUEST_USER = 'REQUEST_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
// ALERTS
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// COMPANY MANAGEMENT
export const ALL_COMPANIES = 'ALL_COMPANIES'
export const GET_COMPANIES_FAIL = 'GET_COMPANIES_FAIL'
// LOADERS
export const LOADING = 'LOADING'
export const STOP_LOADING = 'STOP_LOADING'
// USER MANAGEMENT
export const LOAD_USERS = 'LOAD_USERS'
// STATS
export const FETCH_STATS = 'FETCH_STATS'
// APPS
export const FETCH_APPS = 'FETCH_APPS'
export const RECEIVE_APPS = 'RECEIVE_APPS'
export const FAILED_FETCH_APPS = 'FAILED_FETCH_APPS'
